/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remote_cmd.h"

bool_t
xdr_ClientInput (XDR *xdrs, ClientInput *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->program_name_, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->flags_, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->stdin_, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->part_))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->parts_))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ServerOutput (XDR *xdrs, ServerOutput *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->stdout_, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->stderr_, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status_))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->part_))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->parts_))
		 return FALSE;
	return TRUE;
}
